"""message describing the changes

Revision ID: 7cae220a2809
Revises: 
Create Date: 2024-11-28 02:19:14.505503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cae220a2809'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False, comment='Вопрос'),
    sa.Column('answer', sa.String(), nullable=False, comment='Ответ'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('code_of_chat', sa.BigInteger(), nullable=False, comment='Как бы тоже айдишник, но тот который создает тг'),
    sa.Column('captain_id', sa.String(), nullable=True, comment='Идентификатор капитана команды'),
    sa.Column('points_awarded', sa.Integer(), nullable=True, comment='Количество начисленных очков'),
    sa.Column('question_id', sa.Integer(), nullable=True, comment='Вопрос, задаваемый в раунде'),
    sa.Column('round_number', sa.Integer(), nullable=True, comment='Номер раунда'),
    sa.Column('respondent_id', sa.String(), nullable=True, comment='Идентификатор ответчика команды'),
    sa.Column('is_working', sa.Integer(), nullable=True, comment='активен ли игра в данный момент'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('code_of_chat')
    )
    op.create_table('asked_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Integer(), nullable=False, comment='Вопрос, который был'),
    sa.Column('chat_id', sa.BigInteger(), nullable=False, comment='Идентификатор чата команды'),
    sa.ForeignKeyConstraint(['chat_id'], ['game.code_of_chat'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('int_user_id', sa.BigInteger(), nullable=False, comment='Айдишник пользователя в Telegram'),
    sa.Column('user_id', sa.String(), nullable=False, comment='Имя пользователя в Telegram'),
    sa.Column('chat_id', sa.BigInteger(), nullable=False, comment='Идентификатор чата команды'),
    sa.ForeignKeyConstraint(['chat_id'], ['game.code_of_chat'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('asked_questions')
    op.drop_table('game')
    op.drop_table('questions')
    # ### end Alembic commands ###
