"""Initial migration for tables

Revision ID: 95838d7eb66d
Revises: 8eca344fc222
Create Date: 2024-11-20 17:36:11.504345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95838d7eb66d'
down_revision = '8eca344fc222'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### Создаём таблицы без циклических зависимостей ###
    op.create_table(
        'questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question', sa.String(), nullable=False, comment='Вопрос'),
        sa.Column('answer', sa.String(), nullable=False, comment='Ответ'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор участника команды'),
        sa.Column('chat_id', sa.Integer(), nullable=True, comment='Идентификатор чата команды'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'game',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('captain_id', sa.Integer(), nullable=False, comment='Идентификатор капитана команды'),
        sa.Column('points_awarded', sa.Integer(), nullable=False, comment='Количество начисленных очков'),
        sa.Column('code_of_chat', sa.Integer(), nullable=False, comment='Как бы тоже айдишник, но тот который создает тг'),
        sa.Column('question_id', sa.Integer(), nullable=True, comment='Вопрос, задаваемый в раунде'),
        sa.Column('round_number', sa.Integer(), nullable=False, comment='Номер раунда'),
        sa.Column('respondent_id', sa.Integer(), nullable=True, comment='Идентификатор ответчика команды'),
        sa.ForeignKeyConstraint(['captain_id'], ['users.id']),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id']),
        sa.ForeignKeyConstraint(['respondent_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'asked_questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question', sa.Integer(), nullable=False, comment='Вопрос, который был'),
        sa.Column('chat_id', sa.Integer(), nullable=False, comment='Идентификатор чата команды'),
        sa.ForeignKeyConstraint(['chat_id'], ['game.id']),
        sa.ForeignKeyConstraint(['question'], ['questions.id']),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asked_questions')
    op.drop_table('users')
    op.drop_table('questions')
    op.drop_table('game')
    # ### end Alembic commands ###
