"""ьщььлщл

Revision ID: a90c6dc5f802
Revises: a05a8e6614c7
Create Date: 2024-11-23 08:59:44.250414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90c6dc5f802'
down_revision = 'a05a8e6614c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('is_working', sa.Integer(), nullable=True, comment='активен ли игра в данный момент'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'is_working')
    # ### end Alembic commands ###
